openapi: 3.0.0
info:
  title: Article API
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /articles:
    post:
      summary: Create a new article
      operationId: createArticle
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Article"
      responses:
        "201":
          description: Article created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
    get:
      summary: List all articles
      operationId: readAllArticle
      responses:
        "200":
          description: An array of articles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Article"
  /articles/{articleId}:
    get:
      summary: Get an article by ID
      operationId: readArticle
      parameters:
        - name: articleId
          in: path
          required: true
          description: ID of the article to retrieve
          schema:
            type: string
      responses:
        "200":
          description: The article
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
        "404":
          description: Article not found
    put:
      summary: Update an article by ID
      operationId: updateArticle
      parameters:
        - name: articleId
          in: path
          required: true
          description: ID of the article to update
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Article"
      responses:
        "200":
          description: Article updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
        "404":
          description: Article not found
    delete:
      summary: Delete an article by ID
      operationId: deleteArticle
      parameters:
        - name: articleId
          in: path
          required: true
          description: ID of the article to delete
          schema:
            type: string
      responses:
        "204":
          description: Article deleted
        "404":
          description: Article not found
components:
  schemas:
    Article:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        author:
          type: string
